/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Task = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'rule' : IDL.Text,
  'time' : IDL.Nat,
});
export const StreakData = IDL.Record({
  'lastFocusDate' : IDL.Text,
  'bestStreak' : IDL.Nat,
  'currentStreak' : IDL.Nat,
});
export const FocusSession = IDL.Record({
  'completedAt' : IDL.Int,
  'taskId' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createTask' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [Task], []),
  'deleteTask' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getStreak' : IDL.Func([], [StreakData], ['query']),
  'listFocusSessions' : IDL.Func([], [IDL.Vec(FocusSession)], ['query']),
  'listTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'recordFocusSession' : IDL.Func([IDL.Nat], [FocusSession], []),
  'updateStreak' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [StreakData], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'rule' : IDL.Text,
    'time' : IDL.Nat,
  });
  const StreakData = IDL.Record({
    'lastFocusDate' : IDL.Text,
    'bestStreak' : IDL.Nat,
    'currentStreak' : IDL.Nat,
  });
  const FocusSession = IDL.Record({
    'completedAt' : IDL.Int,
    'taskId' : IDL.Nat,
  });
  
  return IDL.Service({
    'createTask' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [Task], []),
    'deleteTask' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getStreak' : IDL.Func([], [StreakData], ['query']),
    'listFocusSessions' : IDL.Func([], [IDL.Vec(FocusSession)], ['query']),
    'listTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'recordFocusSession' : IDL.Func([IDL.Nat], [FocusSession], []),
    'updateStreak' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [StreakData], []),
  });
};

export const init = ({ IDL }) => { return []; };