/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FocusSession { 'completedAt' : bigint, 'taskId' : bigint }
export interface StreakData {
  'lastFocusDate' : string,
  'bestStreak' : bigint,
  'currentStreak' : bigint,
}
export interface Task {
  'id' : bigint,
  'action' : string,
  'rule' : string,
  'time' : bigint,
}
export interface _SERVICE {
  'createTask' : ActorMethod<[string, bigint, string], Task>,
  'deleteTask' : ActorMethod<[bigint], boolean>,
  'getStreak' : ActorMethod<[], StreakData>,
  'listFocusSessions' : ActorMethod<[], Array<FocusSession>>,
  'listTasks' : ActorMethod<[], Array<Task>>,
  'recordFocusSession' : ActorMethod<[bigint], FocusSession>,
  'updateStreak' : ActorMethod<[bigint, bigint, string], StreakData>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];